/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Oraclep;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import static vista.Inventarios.txtprovee;

/**
 *
 * @author Eparrales
 */
public class DetalleOrden extends javax.swing.JFrame {

        DefaultTableModel modta2;
    Oraclep ora2;
    public DetalleOrden() {
        initComponents();
        modta2 = new DefaultTableModel();
        ora2= new Oraclep();
//        txtidinventa.setEditable(false);
        txtidservi.setEditable(false);
        txtidorden.setEditable(false);
        txtfecha.setEditable(false);
        txtivainsumo.setEditable(false);
        txtivaservicios.setEditable(false);
        soloNum(txtcantinsumos);
        soloNum(txtcantservicios);
        soloNum(txtporcentivaIns);
        soloNum(txtprecioservi);
        soloNum(txtporcentivaser);
        soloNum(txtprecioinsumo);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablagestion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        selectorfecha = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        precioInsumoLabel1 = new javax.swing.JLabel();
        txtidservi = new javax.swing.JTextField();
        precioInsumoLabel = new javax.swing.JLabel();
        txtporcentivaIns = new javax.swing.JTextField();
        idOrdenesLabel = new javax.swing.JLabel();
        txtcantservicios = new javax.swing.JTextField();
        precioServicoLabel = new javax.swing.JLabel();
        txtidinventa = new javax.swing.JTextField();
        txtprecioservi = new javax.swing.JTextField();
        txtcantinsumos = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtporcentivaser = new javax.swing.JTextField();
        ivaInsumoLabel = new javax.swing.JLabel();
        cantidadInsumoLabel = new javax.swing.JLabel();
        txtivaservicios = new javax.swing.JTextField();
        cantidadServiciosLabel = new javax.swing.JLabel();
        txtidorden = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        idInventariosLabel = new javax.swing.JLabel();
        idServiciosLabel = new javax.swing.JLabel();
        txtivainsumo = new javax.swing.JTextField();
        txtprecioinsumo = new javax.swing.JTextField();
        ivaServiciosLabel = new javax.swing.JLabel();
        precioInsumoLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtobserva = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        btnNuevoRegistro = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbcoddetalleord = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnfinalizarord = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Inventarios = new javax.swing.JMenuItem();
        menuModesp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Ordenes = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablagestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablagestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablagestionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablagestion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GESTION DE ORDENES DE SERVICIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        precioInsumoLabel1.setText("Porcentaje iva insumo:");

        precioInsumoLabel.setText("Precio Insumo:");

        idOrdenesLabel.setText("Id  Orden:");

        txtcantservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantserviciosActionPerformed(evt);
            }
        });

        precioServicoLabel.setText("Precio Servico:");

        txtfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfechaMouseClicked(evt);
            }
        });

        ivaInsumoLabel.setText("Iva Insumo:");

        cantidadInsumoLabel.setText("Cantidad Insumo:");

        cantidadServiciosLabel.setText("Cantidad Servicios:");

        fechaLabel.setText("Fecha:");

        idInventariosLabel.setText("Id Inventarios:");

        idServiciosLabel.setText("Id Servicios:");

        ivaServiciosLabel.setText("Iva Servicios:");

        precioInsumoLabel2.setText("Porcentaje iva servicios:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadServiciosLabel)
                    .addComponent(fechaLabel)
                    .addComponent(cantidadInsumoLabel)
                    .addComponent(precioInsumoLabel)
                    .addComponent(ivaInsumoLabel)
                    .addComponent(precioServicoLabel)
                    .addComponent(ivaServiciosLabel)
                    .addComponent(idInventariosLabel)
                    .addComponent(idOrdenesLabel)
                    .addComponent(idServiciosLabel)
                    .addComponent(precioInsumoLabel1)
                    .addComponent(precioInsumoLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidorden, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtidinventa)
                    .addComponent(txtidservi)
                    .addComponent(txtcantinsumos)
                    .addComponent(txtprecioinsumo)
                    .addComponent(txtporcentivaIns)
                    .addComponent(txtporcentivaser)
                    .addComponent(txtivainsumo)
                    .addComponent(txtprecioservi)
                    .addComponent(txtivaservicios)
                    .addComponent(txtcantservicios)
                    .addComponent(txtfecha))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idOrdenesLabel)
                    .addComponent(txtidorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idInventariosLabel)
                    .addComponent(txtidinventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idServiciosLabel)
                    .addComponent(txtidservi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadInsumoLabel)
                    .addComponent(txtcantinsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioInsumoLabel)
                    .addComponent(txtprecioinsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioInsumoLabel1)
                    .addComponent(txtporcentivaIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioInsumoLabel2)
                    .addComponent(txtporcentivaser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ivaInsumoLabel)
                    .addComponent(txtivainsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioServicoLabel)
                    .addComponent(txtprecioservi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ivaServiciosLabel)
                    .addComponent(txtivaservicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadServiciosLabel)
                    .addComponent(txtcantservicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalles de la reparacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        txtobserva.setColumns(20);
        txtobserva.setRows(5);
        jScrollPane3.setViewportView(txtobserva);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)), "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        btnActualizar.setText("Refresh");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        btnNuevoRegistro.setText("Nuevo");
        btnNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRegistroActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoRegistro)
                    .addComponent(saveButton)
                    .addComponent(btnModificar)
                    .addComponent(btnActualizar)
                    .addComponent(btneliminar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lbcoddetalleord.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        lbcoddetalleord.setForeground(new java.awt.Color(0, 0, 255));
        lbcoddetalleord.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("CODIGO:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbcoddetalleord, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcoddetalleord, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnfinalizarord.setText("Finalizar la orden");
        btnfinalizarord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinalizarordActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuItem1.setText("Servicios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Inventarios.setText("Asignacion Insumos");
        Inventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventariosActionPerformed(evt);
            }
        });
        jMenu1.add(Inventarios);

        menuModesp.setText("Modulo Especialistas");
        menuModesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModespActionPerformed(evt);
            }
        });
        jMenu1.add(menuModesp);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Abrir");

        Ordenes.setText("Ordenes");
        Ordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenesActionPerformed(evt);
            }
        });
        jMenu2.add(Ordenes);

        jMenuItem4.setText("Especialistas");
        jMenu2.add(jMenuItem4);

        jMenuItem2.setText("Inventarios");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Imprimir");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Guardar");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1)
                        .addGap(149, 149, 149)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addComponent(btnfinalizarord, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(selectorfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnfinalizarord, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcantserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantserviciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantserviciosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Servicios se = new Servicios();
        se.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void OrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenesActionPerformed
      
       Orden ord = new Orden();
       ord.setVisible(true);
        
        
    }//GEN-LAST:event_OrdenesActionPerformed

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed
        // Limpiar los campos para ingresar un registro nuevo

        limpCampos();

    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String ID_ORDENES, FECHA, OBSERVACIONES, sql;
        int COD_DETALLE, ID_INVENTARIOS, ID_SERVICIOS, CANTIDAD_INSUMO, CANTIDAD_SERVICIOS;
        double PRECIO_INSUMO_SINIVA, IVA_INSUMO, PRECIO_SERVICO, IVA_SERVICIOS;
         ID_INVENTARIOS = Integer.parseInt(txtidinventa.getText());
//        try {
           
            CANTIDAD_INSUMO = Integer.parseInt(txtcantinsumos.getText());
            PRECIO_INSUMO_SINIVA = Double.parseDouble(txtprecioinsumo.getText());
            IVA_INSUMO = getIva(PRECIO_INSUMO_SINIVA, Integer.parseInt(txtporcentivaIns.getText()));

            ID_ORDENES = txtidorden.getText();

            ID_SERVICIOS = Integer.parseInt(txtidservi.getText());

            PRECIO_SERVICO = Double.parseDouble(txtprecioservi.getText());
            IVA_SERVICIOS = getIva(PRECIO_SERVICO, Integer.parseInt(txtporcentivaser.getText()));
            CANTIDAD_SERVICIOS = Integer.parseInt(txtcantservicios.getText());
            FECHA = txtfecha.getText();
            OBSERVACIONES = txtobserva.getText();

            sql = "insert into detalles_ordenes values(null,'" + ID_ORDENES + "'," + ID_INVENTARIOS + "," + ID_SERVICIOS + "," + CANTIDAD_INSUMO + "," + PRECIO_INSUMO_SINIVA + "," + IVA_INSUMO + ","+PRECIO_SERVICO+","+IVA_SERVICIOS+","+CANTIDAD_SERVICIOS+",'"+FECHA+"','"+OBSERVACIONES+"')";
            
            ora2.regisData(sql);
           
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, " ¡Debe llenar todos los campos correctamente !", " Error! ", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String ID_ORDENES, FECHA, OBSERVACIONES, sql;
        int COD_DETALLE, ID_INVENTARIOS, ID_SERVICIOS, CANTIDAD_INSUMO, CANTIDAD_SERVICIOS;
        double PRECIO_INSUMO_SINIVA, IVA_INSUMO, PRECIO_SERVICO, IVA_SERVICIOS;

        try {
            COD_DETALLE= Integer.parseInt(lbcoddetalleord.getText());
            ID_ORDENES = txtidorden.getText();
            ID_INVENTARIOS = Integer.parseInt(txtidinventa.getText());
            ID_SERVICIOS = Integer.parseInt(txtidservi.getText());
            CANTIDAD_INSUMO = Integer.parseInt(txtcantinsumos.getText());
            PRECIO_INSUMO_SINIVA = Double.parseDouble(txtprecioinsumo.getText());

            IVA_INSUMO = getIva(PRECIO_INSUMO_SINIVA, Integer.parseInt(txtporcentivaIns.getText()));
            PRECIO_SERVICO = Double.parseDouble(txtprecioservi.getText());
            IVA_SERVICIOS = getIva(PRECIO_SERVICO, Integer.parseInt(txtporcentivaser.getText()));
            CANTIDAD_SERVICIOS = Integer.parseInt(txtcantservicios.getText());
            FECHA = txtfecha.getText();
            OBSERVACIONES = txtobserva.getText();

            sql = "update  detalles_ordenes set  ID_ORDENES='" + ID_ORDENES + "',ID_INVENTARIOS =" + ID_INVENTARIOS + ",ID_SERVICIOS=" + ID_SERVICIOS + ",CANTIDAD_INSUMO=" + CANTIDAD_INSUMO + ",PRECIO_INSUMO_SINIVA=" + PRECIO_INSUMO_SINIVA + ",IVA_INSUMO=" + IVA_INSUMO + ",PRECIO_SERVICO="+PRECIO_SERVICO+",IVA_SERVICIOS="+IVA_SERVICIOS+",CANTIDAD_SERVICIOS="+CANTIDAD_SERVICIOS+",FECHA='"+FECHA+"',OBSERVACIONES='"+OBSERVACIONES+"' where COD_DETALLE="+COD_DETALLE;
            ora2.regisData(sql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " ¡Debe llenar todos los campos correctamente !", " Error! ", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int cod = Integer.parseInt(lbcoddetalleord.getText());
        String idord=txtidorden.getText();
        String sql;
        int respuesta = JOptionPane.showConfirmDialog(null, " ¿Esta seguro que desea elminiar el registro? " + cod, "Eliminar Registro", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (respuesta) {
            case JOptionPane.YES_OPTION:
                System.out.println("" + respuesta);
                break;
            case JOptionPane.NO_OPTION:

                break;
            case JOptionPane.CANCEL_OPTION:

                break;
        }

        if (respuesta == 0) {

            try {
                sql = "delete detalles_ordenes where  COD_DETALLE="+cod;
                ora2.regisData(sql);
                sql=" Update ordenes set estado='Anulada' where COD_ORDENES='"+idord+"'";
                ora2.regisData(sql);
            } catch (Exception e) {
            }

        }
        refresh();
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        refresh();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void menuModespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModespActionPerformed
        
        ModEspecial aord = new ModEspecial();
        aord.setVisible(true);
        
        
    }//GEN-LAST:event_menuModespActionPerformed

    private void InventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventariosActionPerformed
       InsumosDisponibles asi = new InsumosDisponibles();
       asi.setVisible(true);
         
        
        
    }//GEN-LAST:event_InventariosActionPerformed

    private void tablagestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablagestionMouseClicked
          double valuni,valiva,pi;
          String fe;
  
        int fila = tablagestion.getSelectedRow();
        
            lbcoddetalleord.setText(tablagestion.getModel().getValueAt(fila, 0).toString());
            txtidorden.setText(tablagestion.getModel().getValueAt(fila, 1).toString());
           txtidinventa.setText(tablagestion.getModel().getValueAt(fila, 2).toString());
            txtidservi.setText(tablagestion.getModel().getValueAt(fila, 3).toString());
            txtcantinsumos.setText(tablagestion.getModel().getValueAt(fila, 4).toString());
            txtprecioinsumo.setText(tablagestion.getModel().getValueAt(fila, 5).toString());
            txtivainsumo.setText(tablagestion.getModel().getValueAt(fila, 6).toString());
            valuni=Double.parseDouble(tablagestion.getModel().getValueAt(fila, 5).toString());
            valiva=Double.parseDouble(tablagestion.getModel().getValueAt(fila, 6).toString());
            pi= (valiva/valuni)*100;
            txtporcentivaIns.setText(""+pi);
            txtprecioservi.setText(tablagestion.getModel().getValueAt(fila, 7).toString());
            txtivaservicios.setText(tablagestion.getModel().getValueAt(fila, 8).toString());
             valuni=Double.parseDouble(tablagestion.getModel().getValueAt(fila, 7).toString());
            valiva=Double.parseDouble(tablagestion.getModel().getValueAt(fila, 8).toString());
            pi= (valiva/valuni)*100;
            txtporcentivaser.setText(""+pi);
            txtcantservicios.setText(tablagestion.getModel().getValueAt(fila, 9).toString());
            fe = bdfecha(tablagestion.getModel().getValueAt(fila, 10).toString());
            txtfecha.setText(fe);
             txtobserva.setText(tablagestion.getModel().getValueAt(fila, 11).toString());
        
        
        
    }//GEN-LAST:event_tablagestionMouseClicked

    private void txtfechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfechaMouseClicked
          Date date = selectorfecha.getDate();
         txtfecha.setText(getFechatxt(date));
        
        
    }//GEN-LAST:event_txtfechaMouseClicked

    private void btnfinalizarordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinalizarordActionPerformed
        String sql;
        String idord=txtidorden.getText();
        
        
       
        int respuesta = JOptionPane.showConfirmDialog(null, " ¿ Esta seguro que desea finalizar la orden ? " +idord, "Finalizar orden", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (respuesta) {
            case JOptionPane.YES_OPTION:
             sql=" Update ordenes set estado='Finalizada' where COD_ORDENES='"+idord+"'";
            ora2.regisData(sql);
                
                
            break;
            case JOptionPane.NO_OPTION:

            break;
            case JOptionPane.CANCEL_OPTION:

            break;
        }
        
        
    }//GEN-LAST:event_btnfinalizarordActionPerformed

       // metodos utilitarios
    
     public void refresh(){
          modta2= new DefaultTableModel();
          String sql="select * from detalles_ordenes";
          ora2.consultar(sql);
           
         try {
             int numCol = ora2.getRstmdata().getColumnCount();
             for (int i = 0; i < numCol; i++) {
                 modta2.addColumn(ora2.getRstmdata().getColumnLabel(i + 1));

             }

             while (ora2.getRst().next()) {
                 Object[] fila = new Object[numCol];
                 for (int i = 0; i < numCol; i++) {
                     fila[i] = ora2.getRst().getObject(i + 1);
                 }

                 modta2.addRow(fila);
                 tablagestion.setModel(modta2);
             }

         } catch (Exception e) {
         }
    }
   
    public void limpCampos() {
        lbcoddetalleord.setText("");
        txtidorden.setText("");
        txtidinventa.setText("");
        txtidservi.setText("");
        txtcantinsumos.setText("");
        txtprecioinsumo.setText("");
        txtivainsumo.setText("");
        txtprecioservi.setText("");
        txtivaservicios.setText("");
        txtporcentivaIns.setText("");
        txtporcentivaser.setText("");
        txtcantservicios.setText("");

        txtfecha.setText("");
        txtobserva.setText("");
        
        
        
   
    }
    
    public void soloNum(JTextField tx) {
        tx.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isLetter(c)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }
    public void soloCaract(JTextField tx) {
        tx.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

    }
    
    public void modJtxt(){
      
        
        
    }
    
    
  
    
    public double getIva(double val, int pi){
       
        try {
            
              return val *(pi/100);

        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, " Debe ingresar un valor de iva correcto ", "Error!", JOptionPane.INFORMATION_MESSAGE);
            return 0;

        }

    }
    
    /// Metodos para la manipulacion de las fechas
    public String getFechatxt(Date d){
  
        try {
            String formato = selectorfecha.getDateFormatString();
            //Formato
            
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            String txtfechap = sdf.format(d);
            return txtfechap;
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.INFORMATION_MESSAGE);
            return null;

        }


    
    }
    public Date fechadate(String f){
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat(selectorfecha.getDateFormatString());

        Date fecha;
        try {

            fecha = formatoDelTexto.parse(f);
            return fecha;

        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        return null;
    }
    
    public String bdfecha(String f){
        String fechabd,año="",mes="",dia="";
        for (int i = 0; i < f.length(); i++) {
            if (i < 4) {
                año += f.charAt(i);
            }
            if (i > 4 && i < 7) {
                mes += f.charAt(i);
            }
            if (i > 7 && i < 10) {
                dia += f.charAt(i);
            }
        }

        fechabd=dia+"/"+mes+"/"+año;
        return fechabd;
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new DetalleOrden().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Inventarios;
    private javax.swing.JMenuItem Ordenes;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnfinalizarord;
    private javax.swing.JLabel cantidadInsumoLabel;
    private javax.swing.JLabel cantidadServiciosLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel idInventariosLabel;
    private javax.swing.JLabel idOrdenesLabel;
    private javax.swing.JLabel idServiciosLabel;
    private javax.swing.JLabel ivaInsumoLabel;
    private javax.swing.JLabel ivaServiciosLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbcoddetalleord;
    private javax.swing.JMenuItem menuModesp;
    private javax.swing.JLabel precioInsumoLabel;
    private javax.swing.JLabel precioInsumoLabel1;
    private javax.swing.JLabel precioInsumoLabel2;
    private javax.swing.JLabel precioServicoLabel;
    private javax.swing.JButton saveButton;
    private com.toedter.calendar.JDateChooser selectorfecha;
    private javax.swing.JTable tablagestion;
    public static javax.swing.JTextField txtcantinsumos;
    private javax.swing.JTextField txtcantservicios;
    private javax.swing.JTextField txtfecha;
    public static javax.swing.JTextField txtidinventa;
    public static javax.swing.JTextField txtidorden;
    public static javax.swing.JTextField txtidservi;
    private javax.swing.JTextField txtivainsumo;
    private javax.swing.JTextField txtivaservicios;
    private javax.swing.JTextArea txtobserva;
    private javax.swing.JTextField txtporcentivaIns;
    private javax.swing.JTextField txtporcentivaser;
    private javax.swing.JTextField txtprecioinsumo;
    private javax.swing.JTextField txtprecioservi;
    // End of variables declaration//GEN-END:variables
}
